server:
  port: 8888

spring:
  application:
    name: sp-config-server-app
  docker:
    compose:
      enabled: true
  kafka:
    bootstrap-servers:
      - http://localhost:29092
  cloud:
    bus:
      enabled: true
    config:
      enabled: true
      server:
        git:
          uri: ${GIT_REPO}
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
          try-master-branch: false
          clone-on-start: true
          timeout: 5

logging:
  level:
    org.springframework.cloud: DEBUG

